//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace CFCP.Module.BusinessObjects.CFCP
{

    public partial class PhieuChi : DevExpress.Persistent.BaseImpl.BaseObject
    {
        string fNhanvien_ID;
        public string Nhanvien_ID
        {
            get { return fNhanvien_ID; }
            set { SetPropertyValue<string>(nameof(Nhanvien_ID), ref fNhanvien_ID, value); }
        }
        NhaCungCap fNCC_ID;
        [Association(@"PhieuChiReferencesNhaCungCap")]
        public NhaCungCap NCC_ID
        {
            get { return fNCC_ID; }
            set { SetPropertyValue<NhaCungCap>(nameof(NCC_ID), ref fNCC_ID, value); }
        }
        string fSo;
        public string So
        {
            get { return fSo; }
            set { SetPropertyValue<string>(nameof(So), ref fSo, value); }
        }
        DateTime fNgay;
        [DevExpress.ExpressApp.Model.ModelDefault("EditMask", "dd/MM/yyyy HH:mm"),
DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "{0:dd/MM/yyyy HH:mm}")
]
        public DateTime Ngay
        {
            get { return fNgay; }
            set { SetPropertyValue<DateTime>(nameof(Ngay), ref fNgay, value); }
        }
        decimal fSotien;
        [DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "### ### ### ###"),
DevExpress.ExpressApp.Model.ModelDefault("EditMask","### ### ### ###")]
		public decimal Sotien
        {
            get { return fSotien; }
            set { SetPropertyValue<decimal>(nameof(Sotien), ref fSotien, value); }
        }
    }

}
